### ISSUE TITLE
DefaultRequestHeaders overwritten

### ISSUE THREAD

**Issue by wilversings** [OSLC/oslc4net#19]
All the headers set before a GetResource call are wiped out. I cannot add my own headers

**Comment by berezovskyi** [comment]
Hello Marius,

Thank you for the report. There are no active project maintainers ATM, but we will be glad to do a code review and merge a patch if you could find how to solve your issue.

/Andrew

**Comment by wilversings** [comment]
Hi Andrew
I think I will sometime, thanks

**Comment by berezovskyi** [comment]
Hi @wilversings, we are considering to put some effort into reviving the project and looking for users interested in a .NET OSLC SDK. Could you please contact me via email if you (and/or your company) has a need for a .NET OSLC SDK? My email is visible in my profile.

**Comment by berezovskyi** [comment]
Hi @wilversings,

I finally got to restart working on this library. I indeed traced the header issue to https://github.com/OSLC/oslc4net/blob/fb29da8f3522ce87ad112ebce49b76bd38b6dd1a/OSLC4Net_SDK/OSLC4Net.Client/Oslc/OslcClient.cs#L106 which indicates it was intentional. I think it's associated with the old ways of reusing HTTP client instances.

How would you suggest to fix this? The main problem I see is that the `DefaultRequestHeaders` property would apply to the current and every subsequent request, which could cause problems. I didn't find a method overload for `GetAsync` that would take a dict with request headers for one request only.

One option I see is to [switch to HttpClientFactory](https://stackoverflow.com/questions/61899159/migrating-from-manually-managed-httpclient-with-separate-tokenuri-to-ihttpclie) instead of using a single client for everything. It may even give us thread safety for free.
