### ISSUE TITLE
OSLC4Net in .NET Core or .NET Standard 2.0

### ISSUE THREAD

**Issue by carlosegomezc** [OSLC/oslc4net#25]
Hi,

I see OSLC4Net uses an old .NET Framework and I would like to know if you plan to migrate to a newer version e.g. .NET Core 6 or to .NET Standard 2.0 as supported by dotNetRDF.

Thanks,

**Comment by jadelkhoury** [comment]
@carlosegomezc 

There has been some random interest in OSLC4Net over the years, but unfortunately there is little momentum behind this project. I suspect that some have used and fixed the libraries, but did not contribute back to the SDK.

Maybe you can consider connecting with "[pushpita-sengupta](https://github.com/pushpita-sengupta)" that raised an OSLC4J issue about this recently? 
Please see https://github.com/OSLC/oslc4net/issues/23

**Comment by carlosegomezc** [comment]
@jadelkhoury, thanks for your feedback.  @pushpita-sengupta, have you tried to migrate OSLC4Net?

**Comment by berezovskyi** [comment]
@carlosegomezc @pushpita-sengupta @mwijns in case this project is still relevant for you: I have just finished upgrading the project from .Net 4.5 and ASP.NET MVC 4 with old Nuget management (packages.config & MSBuild-based package restore) to .Net 4.8 and ASP.NET MVC 5 with the modern Nuget management (PackageReference & NuGet 2.7+ Automatic Package Restore).

Also updated `log4net` and `Newtonsoft.Json` to address the CVEs on them. .Net 4.8 and ASP.NET MVC 5 are also still supported, which gives us a minimally usable SDK. As well as a baseline in case some future integration projects would have to rely on .NET Framework due to some legacy considerations.

This should be enough to make the first release on Github and push most of the packages to Nuget, version `0.3.0-alpha`. Then we can move on to converting the libs to .NET Standard (except for the client, perhaps, due to [HTTP classes](https://stackoverflow.com/a/51025423)) and the samples to ASP.NET Core Web API (targeting .Net 7, I guess).

@mwijns CCing you because I saw your earlier fork attempting a move to .NET 5.

@carlosegomezc regarding dotNetRDF, I have made a [conservative update](https://github.com/OSLC/oslc4net/commit/2f65888b3599af3a5e698f0015b187a3e0fecfa4) for now from 1.0.0.2533 to 1.0.13, with a plan to catch up with 2.x and 3.x for the OSLC4Net 0.4.0 milestone, because a [direct migration is failing right now](https://github.com/OSLC/oslc4net/pull/62).

**Comment by berezovskyi** [comment]
@carlosegomezc @pushpita-sengupta @mwijns most libraries are now migrated to `netstandard2.0`, test projects target `net6.0`, `net7.0`, and `net8.0`. The build system uses the `net6.0`/`net7.0`/`net8.0` matrix.

I will close issue for now (resolved via #98 and #109). Feel free to open new issues if you discover any problems with the migration.

**Comment by berezovskyi** [comment]
And yes, we are targeting the latest version of dotNetRDF now: https://github.com/OSLC/oslc4net/pull/110
